package com.revature.entity;

public class Ticket {
    // unique id for each entity
    // this number will be different for every ticket, that way we have a way of uniquely identifying each ticket
    private int id;
    private double amount;
    private String description;
    private String status;
    private int user_id;

    // default constructor:
    public Ticket() {

    }

    // fully parameterized constructor:
    public Ticket(int id, double amount, String description, String status, int user_id) {
        this.id = id; //tickets unique id
        this.amount = amount; // amount of ticket in US currency
        this.description = description; // Description of expense(s)
        this.status = status; // status of ticket
        this.user_id = user_id;
    }

    // a constructor that sets up everything except the id:
    // Why is this important?
    // has to be unique
    // SQL generates these id's for us automatically to be unique
    // when we create a ticket object, we don't want to specify an id because it will be generated by the database anyways
    public Ticket(double amount, String description, String status, int user_id) {
        this.amount = amount;
        this.description = description;
        this.status = status;
        this.user_id = user_id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public double getAmount() {
        return amount;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public String getDescription() {
        return description;
    }
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    @Override
    public String toString() {
        return "Ticket{" +
                "id=" + id +
                ", amount=$'" + amount + '\'' +
                ", description='" + description + '\'' +
                ", status='" + status + '\'' +
                ", user_id='" + user_id + '\'' +
                '}';
    }



}
